[build]
  command = "npx netlify-next build"
  publish = "out"           # Netlify će znati gde je build
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200